docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - Introduction: intro.md
    - "Unit testing with PHPUnit": phpunit.md
    - Assertions: assertions.md
site_name: laminas-test
site_description: laminas-test
repo_url: 'https://github.com/laminas/laminas-test'
extra:
    project: Mvc
    project_url: 'https://docs.laminas.dev'
