docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Introduction: intro.md
    - "Unit testing with PHPUnit": phpunit.md
    - Assertions: assertions.md
site_name: laminas-test
site_description: laminas-test
repo_url: 'https://github.com/laminas/laminas-test'
